Implement Desktop Version
sheezu900/My_Potfolio pull request #11
Opened 2023-06-09 13:21 UTC by sheezu900

### Implement Desktop Version 
**In this PR I implement**
1. The header section
2. The headline section
3. Works section 
4. About my self section
5. contact form

2023-06-09 15:08 UTC, souad988 requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![242722065-db428b0c-8dfc-49c4-a156-42f227e32868](https://github.com/sheezu900/My_Potfolio/assets/59707859/ed380369-a4a2-4550-8ae6-ffc8ceb00f3c)



## Highlights
Good use of grid and flexbosx to layout components
Good PR description

## Required Changes ♻️
_Check the comments under the review._
Also please don't forget to align the contact form button the same way as in the design I'm adding this comment here since i don't have access to it in the file to add inline comment , please refer to the images below

![image (14)](https://github.com/sheezu900/My_Potfolio/assets/59707859/b9261d77-d5ae-4f9b-9881-83b1b82d6082)
![image (15)](https://github.com/sheezu900/My_Potfolio/assets/59707859/319f8fc7-d2e2-4105-9c5b-ac99634e3f6a)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 15:08 UTC, souad988 commented on index.html
>  		<section id="works">
Great work done in this milestone congrats, I have only on thing to mention in this section the image is well positioned 👍🏼  but the info section is not correctly aligned , the margins between items is less than the design and also it doens't cover the same space refer to the images below

![image (10)](https://github.com/sheezu900/My_Potfolio/assets/59707859/33d92267-bc54-4d50-8e56-88f36ccbc5f5)
![image (11)](https://github.com/sheezu900/My_Potfolio/assets/59707859/da2999b8-e2aa-436d-aa21-a953740c993a)

2023-06-09 15:08 UTC, souad988 commented on index.html
> +				<h1>About Myself</h1>
In this section languages list need's to change display direction to horizontal on desktop kindly fix it 

![image (12)](https://github.com/sheezu900/My_Potfolio/assets/59707859/1793f212-01d7-4d06-b3d6-3534655c9832)
![image (13)](https://github.com/sheezu900/My_Potfolio/assets/59707859/7709bdff-ed15-4f92-83b3-ea93f91b4f4d)

2023-06-09 20:43 UTC, Bantealem reviewed
Hi @sheezu900 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a Linters error. Kindly resolve is and request a review for the second time.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-10 06:40 UTC, roshan-bajgain approved these changes
Hi @sheezu900, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Good job on implementing the changes ✔️ 
## Optional suggestions
- [ ] Everyone is facing the `webhint` problem. Hope it will be resolve as soon as possible.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 06:42 UTC, merged