implement Project section and about myself section
sheezu900/My_Potfolio pull request #4
Opened 2023-06-02 14:08 UTC by sheezu900

In this PR I implement:
- Projects Section
- About My Self Section

2023-06-02 14:31 UTC, BregornOriginal requested changes
Hi @sheezu900  

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

![giphy (4)](https://github.com/sheezu900/My_Potfolio/assets/93630700/03301be2-738e-4ef5-92a7-b8c10b074269)

## Highlights

✅ Linters are passing
✅ Good commit history
✅ Good PR title and description

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 14:31 UTC, BregornOriginal commented on style.css
> +  #works {
Good work implementing the works section

- [ ] As this is a requirement, this section should be implemented with `grid`. Grid is an interesting and really useful property to make layouts with CSS. Sometimes will be useful `flex` and other times `grid`, it's for this that you need to implement both of them in this project, to show that you know about how to use them 💯

2023-06-02 14:31 UTC, BregornOriginal commented on index.html
> +						<button class="secondary">See Project</button>
- [ ] Kindly add the following functions to your button in the project. Active, Hover, and Pressed to match with the design provided

![image](https://github.com/sheezu900/My_Potfolio/assets/93630700/f297bae2-0205-43ad-aeba-6e03e511cf25)

2023-06-03 12:01 UTC, Alusp approved these changes
Hi @sheezu900 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congrats](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Highlights

- [x] Good Commit History :green_circle:
- [x]  Professional Readme used :green_circle:
- [x]  No Linter errors :green_circle:
- [x] Professional PR and title :green_circle: 

## Optional suggestions

- [x] Please ensure to add Live demo section in the future,  Including a live demo in the README file demonstrates transparency and builds trust with users. It shows that the project is open and accessible, allowing users to evaluate its functionality without any barriers. This transparency can enhance the credibility of the project and increase user confidence in its quality and reliability. :smiley: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 12:36 UTC, merged